# Generated by Django 4.2.10 on 2024-08-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
