# Generated by Django 4.2.10 on 2024-09-19 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="quantity",
        ),
        migrations.AddField(
            model_name="stock",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stock",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="quantity_in_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
