# Generated by Django 4.2.10 on 2024-09-19 05:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
